/// Flutter icons HugIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HugIcons
///      fonts:
///       - asset: fonts/HugIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class HugIcons {
  HugIcons._();

  static const _kFontFam = 'HugIcons';
  static const String? _kFontPkg = null;

  static const IconData pencil =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
